#!/bin/bash -u
#
# Build the HookAPICost benchmark hooks (src/test/app/hookcost/hookcost.c)
# into src/test/app/HookAPICost_wasm.h.
#
# Prerequisites (same as src/test/app/build_test_hooks.sh):
# - wasmcc   https://github.com/wasienv/wasienv
# - hook-cleaner  https://github.com/RichardAH/hook-cleaner-c
# - clang-format (optional, formats the generated header if present)
# - shasum or sha256sum
#
# Usage: src/test/app/hookcost/build.sh

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

OUTPUT_FILE="../HookAPICost_wasm.h"

# Section names, one per -DB_<name> in hookcost.c
NAMES=(
    base1 base2 base4 base8 base16 base64 basei64 basemem
    fee_base ledger_seq hook_pos hook_pos_k16 float_one otxn_type etxn_generation
    util_sha512h_32 util_sha512h_1k util_sha512h_16k
    state_w_setup_32 state_w_setup_256
    state_r_32 state_r_256
    state_w_32 state_w_create_32 state_w_256
    accept0 rollback0 noexit

    # Phase 2
    util_raddr util_accid
    util_keylet_account util_keylet_child util_keylet_escrow util_keylet_line
    util_keylet_amendments util_keylet_quality
    etxn_burden otxn_burden otxn_generation ledger_last_time ledger_last_hash
    hook_account_api hook_hash_0 hook_hash_neg1 otxn_id_0 otxn_id_1
    float_multiply float_mulratio float_negate float_compare float_compare_le float_sum
    float_invert float_divide float_mantissa float_sign float_int float_log
    float_root float_set float_sto_xrp float_sto_iou float_sto_short
    float_sto_set
    trace_32 trace_1k_hex trace_num trace_float
    otxn_param_32 otxn_param_256 hook_param_32 hook_param_256
    otxn_field_acc otxn_field_1k otxn_field_16k
    otxn_slot_small otxn_slot_1k otxn_slot_16k
    slot_1k slot_16k slot_size slot_type_0 slot_type_1 slot_count
    slot_subfield slot_subarray slot_float slot_set_34 slot_clear
    sto_validate_small sto_subfield_small sto_emplace_small sto_erase_small
    sto_validate_tx sto_subfield_tx sto_subarray_tx sto_emplace_tx sto_erase_tx
    state_foreign_r_32 state_foreign_r_256 state_foreign_w
    etxn_reserve_once hook_again_once ledger_nonce_k200 hook_param_set_k16
    ledger_keylet emit_min_k200
    etxn_nonce_k200 util_verify_ed25519 util_verify_secp256k1 hook_skip_alt util_keylet_hook util_keylet_hook_state util_keylet_skip util_keylet_offer util_keylet_signers util_keylet_check util_keylet_deposit_preauth util_keylet_unchecked util_keylet_owner_dir util_keylet_page util_keylet_paychan util_keylet_emitted_txn util_keylet_nft_offer util_keylet_hook_definition util_keylet_hook_state_dir util_keylet_cron util_keylet_did util_keylet_oracle
    state_w_setup_4k state_r_4k state_w_4k

    # Phase 3
    meta_slot_k200 xpop_slot_k100
    prepare_min prepare_1k etxn_fee_base_1k emit_1k_k200
    util_keylet_amm
)

if ! command -v wasmcc >/dev/null 2>&1; then
    echo "wasmcc not found (https://github.com/wasienv/wasienv)" >&2
    exit 1
fi
if ! command -v hook-cleaner >/dev/null 2>&1; then
    echo "hook-cleaner not found (https://github.com/RichardAH/hook-cleaner-c)" >&2
    exit 1
fi
if command -v shasum >/dev/null 2>&1; then
    SHA256="shasum -a 256"
elif command -v sha256sum >/dev/null 2>&1; then
    SHA256="sha256sum"
else
    echo "neither shasum nor sha256sum found" >&2
    exit 1
fi

WASMCC_VERSION="$(wasmcc --version 2>&1 | head -1)"
HOOK_CLEANER_PATH="$(command -v hook-cleaner)"

{
    echo "// This file is generated by src/test/app/hookcost/build.sh -- do not edit."
    echo "// wasmcc: ${WASMCC_VERSION}"
    echo "// hook-cleaner: ${HOOK_CLEANER_PATH}"
    echo "#ifndef HOOKAPICOST_WASM_INCLUDED"
    echo "#define HOOKAPICOST_WASM_INCLUDED"
    echo "#include <cstdint>"
    echo "#include <map>"
    echo "#include <string>"
    echo "#include <vector>"
    echo "namespace ripple {"
    echo "namespace test {"
    echo "// clang-format off"
    echo "std::map<std::string, std::vector<uint8_t>> hookcost_wasm = {"
} > "$OUTPUT_FILE"

SHA_LINES=()

for name in "${NAMES[@]}"; do
    echo "building B_${name} ..." >&2
    wasm_bytes="$(wasmcc -x c hookcost.c -o /dev/stdout -O2 -Wl,--allow-undefined \
        -I ../../../../hook "-DB_${name}" 2>/tmp/hookcost_build_err.$$ \
        | hook-cleaner - - 2>/dev/null | xxd -p -u -c 1000000 | tr -d '\n')"
    if [ -z "$wasm_bytes" ]; then
        echo "FAILED to build B_${name}:" >&2
        cat /tmp/hookcost_build_err.$$ >&2
        rm -f /tmp/hookcost_build_err.$$
        exit 1
    fi
    rm -f /tmp/hookcost_build_err.$$

    hash="$(echo -n "$wasm_bytes" | xxd -r -p | $SHA256 | cut -d' ' -f1)"
    SHA_LINES+=("    {\"${name}\", \"${hash}\"},")

    hex_bytes="$(echo "$wasm_bytes" | sed -E 's/../0x&U,/g')"
    {
        echo "    {\"${name}\","
        echo "     {"
        echo "         ${hex_bytes}"
        echo "     }},"
    } >> "$OUTPUT_FILE"
done

{
    echo "};"
    echo "std::map<std::string, std::string> hookcost_sha256 = {"
    for line in "${SHA_LINES[@]}"; do
        echo "$line"
    done
    echo "};"
    echo "// clang-format on"
    echo "}  // namespace test"
    echo "}  // namespace ripple"
    echo "#endif"
} >> "$OUTPUT_FILE"

if command -v clang-format >/dev/null 2>&1; then
    clang-format -i "$OUTPUT_FILE" || true
fi

echo "wrote $OUTPUT_FILE" >&2
